# -*- coding: utf-8 -*-
"""DL_ANN_Churn_Modeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t_bBpS4dHz2ztN6x5gqaZGljKVgT3Quz
"""



import pandas as pd
dataset = pd.read_csv("Churn_Modelling.csv")

dataset.shape

dataset.head()

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

features = dataset.iloc[:, 3:13].values
labels = dataset.iloc[:, 13].values

features[1]

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_features_1 = LabelEncoder()
features[:, 1] = labelencoder_features_1.fit_transform(features[:, 1])

labelencoder_features_2 = LabelEncoder()
features[:, 2] = labelencoder_features_2.fit_transform(features[:, 2])

onehotencoder = OneHotEncoder(categorical_features = [1])
features = onehotencoder.fit_transform(features).toarray()

features = features[:, 1:] #dummy variable trap

features[1]

from sklearn.model_selection import train_test_split
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size = 0.2, random_state = 0)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
features_train = sc.fit_transform(features_train)
features_test = sc.transform(features_test)

# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

features.shape

#adding the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

classifier.fit(features_train, labels_train, batch_size = 10, epochs = 10)

labels_pred = classifier.predict(features_test)
labels_pred = (labels_pred > 0.5)

len(labels_pred)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, labels_pred)

cm

"""#**Predict the departure of a customer.**
**Following is the data of the customer**

---

        Credit Score: 600,
        Geography: France,
        Gender: Male,
        Age: 40 years old,
        Tenure: 3 years,
        Balance: $60000,
    Number of Products: 2,
    Does this customer have a credit card? Yes,
    Is this customer an Active Member: Yes?,
    Estimated Salary: $50000
"""

dataset.head()

# This is the user data
user_data=np.array([600,'France','Male',40,3,60000,2,1,1,50000]).reshape(1,-1)
type(user_data)

user_data[:, 1]

# Label encoding the data
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
user_data[:, 1] = labelencoder_features_1.transform(user_data[:, 1])

user_data[:, 2] = labelencoder_features_2.transform(user_data[:, 2])

user_data

# One hot encoding the data
user_data = onehotencoder.transform(user_data).toarray()

user_data = user_data[:, 1:] #dummy variable trap
user_data

user_data

# Scaling the model
user_data = sc.transform(user_data)

user_data

# User Prediction
user_pred=classifier.predict(user_data)
user_pred= user_pred> 0.5
user_pred

if user_pred[0][0]:
  print("User is leaving the bank, Send him amazing offers")
else:
  print('User is not leaving')